
-- tạo ADMIN
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;
/
--Tao user dba QLTGDA (SYS)
CREATE USER QLTGDA IDENTIFIED BY admin;
GRANT ALL PRIVILEGES TO QLTGDA WITH ADMIN OPTION;



GRANT DBA TO QLTGDA;
GRANT CREATE ROLE TO QLTGDA WITH ADMIN OPTION;
GRANT ALTER USER TO QLTGDA WITH ADMIN OPTION;
GRANT CREATE USER TO QLTGDA WITH ADMIN OPTION;
GRANT ALTER ANY ROLE TO QLTGDA WITH ADMIN OPTION;
GRANT DROP USER TO QLTGDA WITH ADMIN OPTION;
GRANT DROP ANY ROLE TO QLTGDA WITH ADMIN OPTION;
GRANT SELECT ANY DICTIONARY TO QLTGDA WITH ADMIN OPTION;
GRANT CREATE ANY VIEW TO QLTGDA WITH ADMIN OPTION;


GRANT EXECUTE ON DBMS_RLS TO QLTGDA;
GRANT EXECUTE ON DBMS_CRYPTO TO QLTGDA;
GRANT EXECUTE ON dbms_fga TO QLTGDA;
GRANT UNLIMITED TABLESPACE TO QLTGDA;

/
--Cap quyen vao bang DBMS_CRYPTO de cai dat ma hoa
GRANT EXECUTE ON SYS.DBMS_CRYPTO TO QLTGDA;
/
--Cap quyen doc audit_trail
GRANT SELECT ON DBA_AUDIT_TRAIL TO QLTGDA;
/
-- tao role
create role SYSADMIN;
GRANT SYSADMIN TO QLTGDA;

CREATE ROLE NHANVIEN;
/
CREATE ROLE QLTRUCTIEP;
/
CREATE ROLE TRUONGPHONG;
/
CREATE ROLE TAICHINH;
/
CREATE ROLE NHANSU;
/
CREATE ROLE TRUONGDA;
/
GRANT SELECT ON DBA_ROLE_PRIVS TO NHANVIEN; 
 
--CS#1: NHAN VIEN 
/
CREATE OR REPLACE VIEW VIEW_NHANVIEN_XEMTHONGTIN_CANHAN
AS
    SELECT *
    FROM NHANVIEN
    WHERE MANV = SYS_CONTEXT('USERENV', 'SESSION_USER');
/
CREATE OR REPLACE VIEW VIEW_NHANVIEN_XEM_THONGTIN_PHONGBAN
AS
    SELECT * 
    FROM PHONGBAN
/
CREATE OR REPLACE VIEW VIEW_NHANVIEN_XEM_THONGTIN_DEAN
AS
    SELECT * 
    FROM DEAN
/
CREATE OR REPLACE VIEW VIEW_TRUONGPHONG_THAOTAC_PHANCONG
 AS
    SELECT PC.* FROM NHANVIEN NV 
    JOIN PHANCONG PC ON NV.MANV = PC.MANV
    WHERE PHG IN (SELECT PHG FROM NHANVIEN WHERE MANV = SYS_CONTEXT('USERENV', 'SESSION_USER'));
/

--GRANT QUYEN ROLE NHANVIEN

GRANT SELECT, UPDATE (TENNV,NGAYSINH,DIACHI,SODT) ON VIEW_NHANVIEN_XEMTHONGTIN_CANHAN TO NHANVIEN;
/
GRANT SELECT ON VIEW_NHANVIEN_XEM_THONGTIN_PHONGBAN TO NHANVIEN;
/
GRANT SELECT ON VIEW_NHANVIEN_XEM_THONGTIN_DEAN TO NHANVIEN;
/
GRANT SELECT ON PHANCONG TO NHANVIEN; --(CAN CAI DAT VPD_1) 

--CS#2: QL TRUC TIEP
/
GRANT NHANVIEN TO TRUONGPHONG;
/
GRANT SELECT ON NHANVIEN TO QLTRUCTIEP; --(CAN CAI DAT VPD_2)
  --GRANT SELECT ON PHANCONG TO QLTRUCTIEP;(đã kế thừa từ NHANVIEN) --(CAN CAI DAT VPD_1)

--CS#3: TRUONG PHONG
/
CREATE OR REPLACE VIEW VIEW_TRUONGPHONG_THONGTIN_PHANCONG 
AS
    SELECT PC.*
    FROM NHANVIEN NV 
    JOIN PHANCONG PC ON NV.MANV = PC.MANV
    WHERE PHG IN (SELECT PHG FROM NHANVIEN WHERE MANV = SYS_CONTEXT('USERENV', 'SESSION_USER'));

/
GRANT NHANVIEN TO TRUONGPHONG; 
/
GRANT SELECT, UPDATE, DELETE ON VIEW_TRUONGPHONG_THONGTIN_PHANCONG TO TRUONGPHONG;
/
GRANT SELECT ON NHANVIEN TO TRUONGPHONG; --(CAN CAI DAT VPD_2)
/
--CS#4: TAI CHINH
GRANT NHANVIEN TO TAICHINH; 
  -- TẠO TRIGGER XỬ L�? CHỔ CHỈ UPDATE LUONG NV - GIAM DOC
/

--CS#5: NhanSu

GRANT NHANVIEN TO NHANSU;
/
GRANT INSERT, UPDATE ON PHONGBAN TO NHANSU;
/   
GRANT UPDATE (MANV,TENNV,PHAI,NGAYSINH,DIACHI,SODT,VAITRO,MANQL,PHG) ON NHANVIEN TO NHANSU;
    -- cài đặt proc để insert, update The Nhan vien với lương và phụ cấp có gt là NULL 
-- cài đặt VBP_3 để hiển thị NULL các trư�?ng LUONG + PHUCAP

--CS#6: TRUONG DE AN
CREATE OR REPLACE VIEW VIEW_HIENTHI_ALL_DEAN
AS  
    SELECT * FROM DEAN;
/
GRANT NHANVIEN TO TRUONGDA;
/
GRANT INSERT, UPDATE, DELETE ON VIEW_HIENTHI_ALL_DEAN TO TRUONGDA;



--CS#7: GIAM DOC ( KO CAI DAT )






