
-- tạo ADMIN
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;
/
--Tao user dba QLTGDA (SYS)
CREATE USER QLTGDA IDENTIFIED BY admin;
GRANT ALL PRIVILEGES TO QLTGDA;
GRANT DBA TO QLTGDA;
/
--Cap quyen vao bang DBMS_CRYPTO de cai dat ma hoa
GRANT EXECUTE ON SYS.DBMS_CRYPTO TO QLTGDA;
/

--Cap quyen doc audit_trail
GRANT SELECT ON DBA_AUDIT_TRAIL TO QLTGDA;
/
-- tao role
CREATE ROLE NHANVIEN;
/
CREATE ROLE QLTRUCTIEP;
/
CREATE ROLE TRUONGPHONG;
/
CREATE ROLE TAICHINH;
/
CREATE ROLE NHANSU;
/
CREATE ROLE TRUONGDA;
/

--CS#1: NHAN VIEN 

CREATE OR REPLACE VIEW VIEW_NHANVIEN_XEMTHONGTIN_CANHAN
AS
    SELECT *
    FROM NHANVIEN
    WHERE MANV = SYS_CONTEXT('USERENV', 'SESSION_USER');
/
CREATE OR REPLACE VIEW VIEW_NHANVIEN_XEM_THONGTIN_PHONGBAN
AS
    SELECT * 
    FROM PHONGBAN
/
CREATE OR REPLACE VIEW VIEW_NHANVIEN_XEM_THONGTIN_DEAN
AS
    SELECT * 
    FROM DEAN
/
CREATE OR REPLACE VIEW VIEW_TRUONGPHONG_THAOTAC_PHANCONG
 AS
    SELECT PC.* FROM NHANVIEN NV 
    JOIN PHANCONG PC ON NV.MANV = PC.MANV
    WHERE PHG IN (SELECT PHG FROM NHANVIEN WHERE MANV = SYS_CONTEXT('USERENV', 'SESSION_USER'));
/

--GRANT QUYEN ROLE NHANVIEN

GRANT SELECT, UPDATE (NGAYSINH,DIACHI,SODT) ON VIEW_NHANVIEN_XEMTHONGTIN_CANHAN TO RL_NHANVIEN;
/
GRANT SELECT ON VIEW_NHANVIEN_XEM_THONGTIN_PHONGBAN TO NHANVIEN;
/
GRANT SELECT ON VIEW_NHANVIEN_XEM_THONGTIN_DEAN TO NHANVIEN;
/
GRANT SELECT ON PHANCONG TO NHANVIEN; --(CAN CAI DAT VPD_1) 

--CS#2: QL TRUC TIEP
/
GRANT NHANVIEN TO TRUONGPHONG;
/
GRANT SELECT ON NHANVIEN TO QLTRUCTIEP; --(CAN CAI DAT VPD_2)
  --GRANT SELECT ON PHANCONG TO QLTRUCTIEP;(DA KE THUA TU NHANVIEN) --(CAN CAI DAT VPD_1)

--CS#3: TRUONG PHONG
/
CREATE OR REPLACE VIEW VIEW_TRUONGPHONG_THONGTIN_PHANCONG 
AS
    SELECT PC.*
    FROM NHANVIEN NV 
    JOIN PHANCONG PC ON NV.MANV = PC.MANV
    WHERE PHG IN (SELECT PHG FROM NHANVIEN WHERE MANV = SYS_CONTEXT('USERENV', 'SESSION_USER'));

/
GRANT NHANVIEN TO TRUONGPHONG; 
/
GRANT SELECT, UPDATE, DELETE ON VIEW_TRUONGPHONG_THONGTIN_PHANCONG TO TRUONGPHONG;
/
GRANT SELECT ON NHANVIEN TO TRUONGPHONG; --(CAN CAI DAT VPD_2)
/
--CS#4: TAI CHINH
GRANT NHANVIEN TO TAICHINH; 
  -- TẠO TRIGGER XỬ LÍ CHỔ CHỈ UPDATE LUONG NV - GIAM DOC
/

--CS#5: TRUONG DE AN
CREATE OR REPLACE VIEW VIEW_HIENTHI_ALL_DEAN
AS  
    SELECT * FROM DEAN;
/
GRANT NHANVIEN TO TRUONGDA;
/
GRANT INSERT, UPDATE, DELETE ON VIEW_HIENTHI_ALL_DEAN TO TRUONGDA;


--CS#6: GIAM DOC ( KO CAI DAT )



