
-- tạo ADMIN
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;
/
--Tao user dba QLTGDA (SYS)
CREATE USER QLTGDA IDENTIFIED BY admin;

GRANT ALL PRIVILEGES TO QLTGDA WITH ADMIN OPTION;


GRANT DBA TO QLTGDA;
GRANT CREATE ROLE TO QLTGDA WITH ADMIN OPTION;
GRANT ALTER USER TO QLTGDA WITH ADMIN OPTION;
GRANT CREATE USER TO QLTGDA WITH ADMIN OPTION;
GRANT ALTER ANY ROLE TO QLTGDA WITH ADMIN OPTION;
GRANT DROP USER TO QLTGDA WITH ADMIN OPTION;
GRANT DROP ANY ROLE TO QLTGDA WITH ADMIN OPTION;
GRANT SELECT ANY DICTIONARY TO QLTGDA WITH ADMIN OPTION;
GRANT CREATE ANY VIEW TO QLTGDA WITH ADMIN OPTION;


GRANT EXECUTE ON DBMS_RLS TO QLTGDA;
GRANT EXECUTE ON DBMS_CRYPTO TO QLTGDA;
GRANT EXECUTE ON dbms_fga TO QLTGDA;
GRANT UNLIMITED TABLESPACE TO QLTGDA;

/
--Cap quyen vao bang DBMS_CRYPTO de cai dat ma hoa
GRANT EXECUTE ON SYS.DBMS_CRYPTO TO QLTGDA;
/
--Cap quyen doc audit_trail
GRANT SELECT ON DBA_AUDIT_TRAIL TO QLTGDA;
/

-- tao role
create role SYSADMIN;
GRANT SYSADMIN TO QLTGDA;

CREATE ROLE NHANVIEN;
/
CREATE ROLE QLTRUCTIEP;
/
CREATE ROLE TRUONGPHONG;
/
CREATE ROLE TAICHINH;
/
CREATE ROLE NHANSU;
/
CREATE ROLE TRUONGDA;
/
GRANT SELECT ON DBA_ROLE_PRIVS TO NHANVIEN; 
 
--CS#1: NHAN VIEN 
/
CREATE OR REPLACE VIEW VIEW_NHANVIEN_XEMTHONGTIN_CANHAN
AS
    SELECT *
    FROM NHANVIEN
    WHERE MANV = SYS_CONTEXT('USERENV', 'SESSION_USER');
/
CREATE OR REPLACE VIEW VIEW_NHANVIEN_XEM_THONGTIN_PHONGBAN
AS
    SELECT * 
    FROM PHONGBAN
/
CREATE OR REPLACE VIEW VIEW_NHANVIEN_XEM_THONGTIN_DEAN
AS
    SELECT * 
    FROM DEAN
/

CREATE OR REPLACE VIEW VIEW_TRUONGPHONG_THAOTAC_PHANCONG
 AS
    SELECT PC.* FROM NHANVIEN NV 
    JOIN PHANCONG PC ON NV.MANV = PC.MANV
    WHERE PHG IN (SELECT PHG FROM NHANVIEN WHERE MANV = SYS_CONTEXT('USERENV', 'SESSION_USER'));
/

--GRANT QUYEN ROLE NHANVIEN

GRANT SELECT ON DBA_ROLE_PRIVS TO NHANVIEN; 
/
GRANT UPDATE(TENNV,DIACHI,NGAYSINH,SODT) ON NHANVIEN TO NHANVIEN;
/
GRANT SELECT, UPDATE (TENNV,NGAYSINH,DIACHI,SODT) ON VIEW_NHANVIEN_XEMTHONGTIN_CANHAN TO NHANVIEN;
/
GRANT SELECT ON VIEW_NHANVIEN_XEM_THONGTIN_PHONGBAN TO NHANVIEN;
/
GRANT SELECT ON VIEW_NHANVIEN_XEM_THONGTIN_DEAN TO NHANVIEN;
/
GRANT SELECT ON PHANCONG TO NHANVIEN; --(CAN CAI DAT VPD_1) 

--CS#2: QL TRUC TIEP
/
GRANT NHANVIEN TO TRUONGPHONG;
/
GRANT SELECT ON NHANVIEN TO QLTRUCTIEP; --(CAN CAI DAT VPD_2)
  --GRANT SELECT ON PHANCONG TO QLTRUCTIEP;(đã kế thừa từ NHANVIEN) --(CAN CAI DAT VPD_1)

--CS#3: TRUONG PHONG
/
CREATE OR REPLACE VIEW VIEW_TRUONGPHONG_THONGTIN_PHANCONG 
AS
    SELECT PC.*
    FROM NHANVIEN NV 
    JOIN PHANCONG PC ON NV.MANV = PC.MANV
    WHERE PHG IN (SELECT MAPB FROM PHONGBAN WHERE TRPHG = SYS_CONTEXT('USERENV', 'SESSION_USER'));

/
GRANT NHANVIEN TO TRUONGPHONG; 
/
GRANT SELECT, UPDATE, DELETE ON VIEW_TRUONGPHONG_THONGTIN_PHANCONG TO TRUONGPHONG;
/
GRANT SELECT ON NHANVIEN TO TRUONGPHONG; --(CAN CAI DAT VPD_2)
/
--CS#4: TAI CHINH
GRANT NHANVIEN TO TAICHINH; 
GRANT SELECT , UPDATE(LUONG,PHUCAP) ON NHANVIEN TO TAICHINH;
  -- TẠO TRIGGER XỬ L�? CHỔ CHỈ UPDATE LUONG NV - GIAM DOC
/
UPDATE NHANVIEN SET LUONG = '2000000' WHERE MANV = 'NV001'

--CS#5: NhanSu
/
GRANT NHANVIEN TO NHANSU;
/
GRANT INSERT, UPDATE ON PHONGBAN TO NHANSU;
/   
GRANT UPDATE (MANV,TENNV,PHAI,NGAYSINH,DIACHI,SODT,VAITRO,MANQL,PHG) ON NHANVIEN TO NHANSU;
    -- cài đặt proc để insert, update The Nhan vien với lương và phụ cấp có gt là NULL 
-- cài đặt VBP_3 để hiển thị NULL các trư�?ng LUONG + PHUCAP

--CS#6: TRUONG DE AN
CREATE OR REPLACE VIEW VIEW_HIENTHI_ALL_DEAN
AS  
    SELECT * FROM DEAN;
/
GRANT NHANVIEN TO TRUONGDA;
/
GRANT INSERT, UPDATE, DELETE ON VIEW_HIENTHI_ALL_DEAN TO TRUONGDA;

SELECT * FROM USER_PRIVES

--CS#7: GIAM DOC ( KO CAI DAT )


-- VPD_1 : role nhân viên xem được phân công của cá nhân 
--         role nhan viên quản lý trực tiếp xem thêm được phân công nhân vien mình quản lý
-- ĐĂNG NHAP VOi QLTGDA/admin


CREATE OR REPLACE VIEW UV_NHANVIEN_XEM_DSPHANCONG
AS 
SELECT NHANVIEN.MANV, NHANVIEN.TENNV, PHANCONG.MADA, PHANCONG.THOIGIAN
FROM PHANCONG JOIN NHANVIEN ON PHANCONG.MANV = NHANVIEN.MANV 
WHERE SYS_CONTEXT('USERENV','SESSION_USER') = NHANVIEN.MANQL 
OR SYS_CONTEXT('USERENV','SESSION_USER') = NHANVIEN.MANV; 
/
GRANT SELECT ON UV_NHANVIEN_XEM_DSPHANCONG TO NHANVIEN;


--VPD_2 : XEM DANH SÁCH NHÂN VIEN MÌNH QUẢN LÝ ( TRƯỞNG PHÒNG + QUAN Lý TRỰC TIẾP)
--CS2:
-- ĐĂNG NHAP VOi QLTGDA/admin

GRANT SELECT ON UV_XEMDS_NHANVIEN TO NHANVIEN;

CREATE OR REPLACE VIEW UV_XEMDS_NHANVIEN
AS 
SELECT * FROM NHANVIEN
WHERE SYS_CONTEXT('USERENV','SESSION_USER') = MANQL 
OR SYS_CONTEXT('USERENV','SESSION_USER') = MANV 
--OR PHG IN ( SELECT PB.MAPB FROM PHONGBAN PB WHERE TRPHG = SYS_CONTEXT('USERENV','SESSION_USER'));
/
CREATE OR REPLACE FUNCTION POL_FUNCTION (P_SCHEMA VARCHAR2, P_OBJ VARCHAR2)
RETURN VARCHAR2
AS 
    USER VARCHAR2(100);
BEGIN
    USER:=SYS_CONTEXT('USERENV', 'SESSION_USER');
    RETURN 'MANV = '''||USER||''''; 
END;
/

begin
    DBMS_RLS.ADD_POLICY(
        OBJECT_SCHEMA => 'QLTGDA',
        OBJECT_NAME => 'UV_XEMDS_NHANVIEN',
        POLICY_NAME => 'POLICY_XEM_DS_NV',
        POLICY_FUNCTION => 'POL_FUNCTION',
        STATEMENT_TYPES => 'SELECT',
        SEC_RELEVANT_COLS =>'LUONG, PHUCAP',
        SEC_RELEVANT_COLS_OPT => dbms_rls.ALL_ROWS
    );
end;
/
CREATE OR REPLACE VIEW UV_TRUONGPHONG_XEM_DS_NHANVIEN AS
    SELECT *
    FROM NHANVIEN
    WHERE PHG IN (SELECT PB.MAPB FROM PHONGBAN PB WHERE TRPHG = SYS_CONTEXT('USERENV', 'SESSION_USER'));
/
GRANT SELECT ON UV_TRUONGPHONG_XEM_DS_NHANVIEN TO TRUONGPHONG;
/
begin
    DBMS_RLS.ADD_POLICY(
        OBJECT_SCHEMA => 'QLTGDA',
        OBJECT_NAME => 'UV_TRUONGPHONG_XEM_DS_NHANVIEN',
        POLICY_NAME => 'POLICY_TRUONGPHONG_NHANVIEN',
        POLICY_FUNCTION => 'POL_FUNCTION',
        STATEMENT_TYPES => 'SELECT',
        SEC_RELEVANT_COLS =>'LUONG, PHUCAP',
        SEC_RELEVANT_COLS_OPT => dbms_rls.ALL_ROWS
    );
end;
--vpd3: Nhân sự xem danh sách , thông tin nhân viên trừ lương, phu cấp
-- ĐĂNG NHAP VOi QLTGDA/admin

/
CREATE OR REPLACE VIEW UV_NHANSU_XEM_DS_NHANVIEN 
AS SELECT * FROM NHANVIEN;
/
GRANT SELECT ON UV_NHANSU_XEM_DS_NHANVIEN TO NHANSU;

begin
    DBMS_RLS.ADD_POLICY(
        OBJECT_SCHEMA => 'QLTGDA',
        OBJECT_NAME => 'UV_NHANSU_XEM_DS_NHANVIEN',
        POLICY_NAME => 'POLICY_NHANSU_XEM_LIST_NHANVIEN',
        POLICY_FUNCTION => 'POL_FUNCTION',
        STATEMENT_TYPES => 'SELECT',
        SEC_RELEVANT_COLS =>'LUONG, PHUCAP',
        SEC_RELEVANT_COLS_OPT => dbms_rls.ALL_ROWS,
        UPDATE_CHECK => TRUE
    );
end;




SELECT * FROM NHANVIEN
